services:
  # Redis Service
  redis_db:
    image: redis:alpine
    container_name: redis_geofence
    ports:
      - "6379:6379"
    restart: always

  # Our app
  geofence_app:
    build: .
    container_name: geofence_service
    depends_on:
      - redis_db
    environment:
      - REDIS_HOST=redis_db # be careful !
      - REDIS_PORT=6379
    restart: on-failure